# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Chat.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'Chat.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nChat.proto\x12\x04\x63hat\"C\n\x0eMessageRequest\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\x12\x0e\n\x06sender\x18\x02 \x01(\t\x12\x10\n\x08receiver\x18\x03 \x01(\t\"\"\n\x0fMessageResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x18\n\x06UserID\x12\x0e\n\x06userid\x18\x01 \x01(\t\"?\n\x14UsersIDsListResponse\x12\'\n\x0cuserIDsLists\x18\x01 \x03(\x0b\x32\x11.chat.UserIDsList\"\"\n\x0bUserIDsList\x12\x13\n\x0buserIdsList\x18\x01 \x03(\t2\x98\x01\n\x13RealTimeChatService\x12:\n\x0bSendMessage\x12\x14.chat.MessageRequest\x1a\x15.chat.MessageResponse\x12\x45\n\x19GetUserFollowingFollowers\x12\x0c.chat.UserID\x1a\x1a.chat.UsersIDsListResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Chat_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MESSAGEREQUEST']._serialized_start=20
  _globals['_MESSAGEREQUEST']._serialized_end=87
  _globals['_MESSAGERESPONSE']._serialized_start=89
  _globals['_MESSAGERESPONSE']._serialized_end=123
  _globals['_USERID']._serialized_start=125
  _globals['_USERID']._serialized_end=149
  _globals['_USERSIDSLISTRESPONSE']._serialized_start=151
  _globals['_USERSIDSLISTRESPONSE']._serialized_end=214
  _globals['_USERIDSLIST']._serialized_start=216
  _globals['_USERIDSLIST']._serialized_end=250
  _globals['_REALTIMECHATSERVICE']._serialized_start=253
  _globals['_REALTIMECHATSERVICE']._serialized_end=405
# @@protoc_insertion_point(module_scope)
