export const CREATE = 'CREATE';
export const UPDATE = 'UPDATE';
export const DELETE = 'DELETE';
export const FETCH_ALL = 'FETCH_ALL';
export const FETCH_MORE = 'FETCH_MORE';
export const FETCH_BY_SEARCH = 'FETCH_BY_SEARCH';
export const FETCH_POST = 'FETCH_POST';
export const LIKE = 'LIKE';
export const COMMENT = 'COMMENT';
export const END_LOADING = 'END_LOADING';
export const START_LOADING = 'START_LOADING';
export const FETCH_BY_CREATOR = 'FETCH_BY_CREATOR';

//
export const AUTH = 'AUTH';
export const LOGOUT = 'LOGOUT';
export const GET_USER_DATA = 'GET_USER_DATA';
export const AUTH_ERROR = 'AUTH_ERROR';

//CHAT
export const SEND_MESSAGE = 'SEND_MESSAGE';
export const GET_UNREADED_MESSAGE = 'GET_UNREADED_MESSAGE';
export const GET_MSG_BETWEEN_TWO_USERS_BY_NUM = 'GET_MSG_BETWEEN_TWO_USERS_BY_NUM';
export const MARK_MSG_AS_READED = 'MARK_MSG_AS_READED';
export const GET_CHAT_LIST_USERS = 'GET_CHAT_LIST_USERS';
export const CLEAR_UN_READED_MSG = 'CLEAR_UN_READED_MSG';

export const GET_NOTIFICATIONS_FOR_USER = 'GET_NOTIFICATIONS_FOR_USER';
export const MARK_NOTIFICATIONS_AS_READED = 'MARK_NOTIFICATIONS_AS_READED';

//REALTIME
export const UPDATE_ONLINE_USERS = 'UPDATE_ONLINE_USERS';

export const START_NOTIFICATION_CONNECTION = 'START_NOTIFICATION_CONNECTION';
export const UPDATE_RECEVE_NOTIFICATIONS = 'UPDATE_RECEVE_NOTIFICATIONS';


